language: python
python:
    - "3.7"

services:
    - docker

before_script: 
    - pip install docker-compose
    - docker build --target production --tag todo-app:prod .
    - docker run -d -p 127.0.0.1:8000:8000 --env-file .env todo-app:prod
    - docker ps -a

script: 
    - docker-compose exec -T todo-app:prod pytest
    